# Generated by Django 6.0.1 on 2026-02-02 23:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='Equipo',
            new_name='Team',
        ),
    ]
